from Administracion import Administracion
from Ventas import Ventas

admin = Administracion()
admin.setNombres(input("Ingrese Nombre del Administrador: "))
admin.setApellidos(input("Ingrese Apellido: "))
admin.setTelefono(int(input("Ingrese Telefono: ")))
admin.setDirec(input("Ingrese Dirección: "))
admin.setGenero(input("Ingrese Género: "))
admin.setCod(int(input("Ingrese Código: ")))
admin.setUsuario(input("Ingrese Usuario: "))
admin.setContraseña(input("Ingrese Contraseña: "))
admin.setSueldoBa(float(input("Ingrese Sueldo Base: ")))
admin.setBoni(float(input("Ingrese Bonificacion: ")))
admin.setPuesto(input("Ingrese puesto: "))
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Datos del Administrador: ")
print("Nombre: ",admin.getNombres())
print("Apellido: ", admin.getApellidos())
print("Telefono: ", admin.getTelefono())
print("Dirección: ", admin.getDirec())
print("Género: ", admin.getGenero())
print("Código: ",admin.getCod())
print("Usuario: ", admin.getUsuario())
print("Contraseña: ",admin.getContraseña())
print("Sueldo Base: ",admin.getSueldoBa())
print("Bonificación: ",admin.getBoni())
print("Puesto: ",admin.getPuesto())
print("Sueldo Liquido: ",admin.getSueldoLi())
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Datos de Vendedor: ")
vendedor = Ventas()
vendedor.setNombres(input("Ingrese Nombre del Vendedor: "))
vendedor.setApellidos(input("Ingrese Apellido: "))
vendedor.setTelefono(int(input("Ingrese Telefono: ")))
vendedor.setDirec(input("Ingrese Dirección: "))
vendedor.setGenero(input("Ingrese Género: "))
vendedor.setCod(int(input("Ingrese Código: ")))
vendedor.setUsuario(input("Ingrese Usuario: "))
vendedor.setContraseña(input("Ingrese Contraseña: "))
vendedor.setTotalVent(float(input("Ingrese Total de Ventas: ")))
vendedor.setPorComision(float(input("Ingrese Porcentaje de comisión: ")))
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Datos del Vendedor: ")
print("Nombre: ",vendedor.getNombres())
print("Apellido: ", vendedor.getApellidos())
print("Telefono: ", vendedor.getTelefono())
print("Dirección: ", vendedor.getDirec())
print("Género: ", vendedor.getGenero())
print("Código: ",vendedor.getCod())
print("Usuario: ", vendedor.getUsuario())
print("Contraseña: ",vendedor.getContraseña())
print("Sueldo Base: ",vendedor.getTotalVent())
print("Bonificación: ",vendedor.getPorComision())
print("Liquido (3'%' de ventas): ",vendedor.getSuelLiquido())